[project]
name = "metabeta"
version = "0.2"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bambi>=0.17.2",
    "datasets>=4.4.1",
    "joblib>=1.5.2",
    "matplotlib>=3.10.7",
    "openml>=0.15.1",
    "pmlb>=1.0.1.post3",
    "pytest>=9.0.2",
    "schedulefree>=1.4.1",
    "scipy>=1.16.3",
    "seaborn>=0.13.2",
    "spyder-kernels>=3.1.2",
    "tensorboard>=2.20.0",
    "torch>=2.9.1",
]

[tool.setuptools.packages.find]
where = ["."]
