summarizer:
    type: 'set-transformer'
    d_model: 32
    d_ff: 64
    d_output: 16
    n_blocks: 2
    n_isab: 0
    activation: 'GELU'
    dropout: 0.01

posterior:
    type: 'coupling'
    transform: 'affine'
    base_family: 'normal'
    base_trainable: True
    n_blocks: 3
    subnet_kwargs:
        net_type: 'mlp'
        activation: 'ReLU'
        d_ff: 64
        depth: 2
        dropout: 0.0
        zero_init: True
        use_bias: False